### ISSUE TITLE
Return value of get_next_run is not very intiutive

### ISSUE THREAD

**Issue by TBail** [spacemanspiff2007/eascheduler#4]
To see if a countdown has expired one cpould use the get_next_run method. Expectation is as follows. If the Countdown is running the returned datetime is in the future, else it is in the past. Unfortunately it return a date > 2038 (Unix tick counter overflow?).

So this is in the future as well as the date for a running count down. Due to the fact that it returns some date in 2038 it could not compared tp datetime.max which is 9999 ...

It would be nice to have a simple boolean method like is_expired

**Comment by spacemanspiff2007** [comment]
There was some more discussion in the [HABApp issue](https://github.com/spacemanspiff2007/HABApp/issues/265)
